@echo off
cd /d "C:\Users\34655\IdeaProjects\ciutats_prov_pais"
echo Añadiendo archivos...
git add -A
echo Haciendo commit...
git commit -m "Listas HTML para provincias, paises y fiestas. Imagenes. CSS unificado. Rutas corregidas."
echo Configurando remote...
git remote set-url origin https://github.com/Pausiar/JavaJPA.git 2>nul || git remote add origin https://github.com/Pausiar/JavaJPA.git
echo Subiendo a GitHub...
git push -u origin main
echo.
echo Completado!
pause
